# Generated by Django 4.2.30 on 2026-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_code', models.CharField(blank=True, max_length=5, null=True)),
                ('strength', models.IntegerField(default=0)),
                ('websites', models.URLField(blank=True)),
            ],
        ),
    ]
