# Generated by Django 4.2.30 on 2026-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
